#!/bin/bash
 
/usr/bin/security authorizationdb write system.preferences.printing allow

/usr/bin/security authorizationdb write system.print.operator allow

/usr/sbin/dseditgroup -o edit -n /Local/Default -a everyone -t group lpadmin

/usr/sbin/dseditgroup -o edit -n /Local/Default -a everyone -t group _lpadmin

## Create dummy receipt to mark complete
touch /Library/Receipts/com.twcs.lpadminadded.bom

exit 0;
